### ISSUE TITLE
Build instructions for ESP32_Protobuf

### ISSUE THREAD

**Issue by georgik** [MehmetTopuz/Protobuf-example-with-ESP32-and-QT#2]
@MehmetTopuz  Nice article about the solution at Medium. 

Please, could you provide a build instructions/README on how to compile the project?

I was trying to build it from command line using `idf.py build`, but it failed with:
```
cd ESP32_Protobuf
idf.py build
....
esp-idf/components/freertos/app_startup.c:199:(.text.main_task+0x99): undefined reference to `app_main'
```

The second attempt with PlatformIO failed with:
`UnknownBoard: Unknown board ID 'upesy_wroom'`

**Comment by MehmetTopuz** [comment]
I am working on Readme. Also, I used ESP32-WROOM-32D on this example.

**Comment by MehmetTopuz** [comment]
Hi @georgik , 
I have added a [readme](https://github.com/MehmetTopuz/Protobuf-example-with-ESP32-and-QT?tab=readme-ov-file#how-to-build-esp32-project) file on how to compile for ESP32, I hope it will be useful.
